filter:
  dependency_paths: [vendor/]
checks:
  php: true
tools:
  external_code_coverage:
    timeout: 900
    runs: 2
build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
