version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foundry
    ports:
      - 33061:3306

  mongo:
    image: mongo:4
    ports:
      - 27017:27017
