version: '3.9'

services:
    php8.0: &php
        container_name: foundry_php8.0
        image: ghcr.io/zenstruck/foundry/php:8.0
        depends_on:
            mysql:
                condition: service_healthy
            mongo:
                condition: service_healthy
        volumes:
            - .:/app
        working_dir: /app
        environment:
            PHP_IDE_CONFIG: "serverName=FOUNDRY"

    php8.1:
        <<: *php
        container_name: foundry_php8.1
        image: ghcr.io/zenstruck/foundry/php:8.1

    php8.2:
        <<: *php
        container_name: foundry_php8.2
        image: ghcr.io/zenstruck/foundry/php:8.2

    mysql:
        container_name: foundry_mysql
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: zenstruck_foundry
        ports:
            - ${MYSQL_PORT:-3306}:3306
        healthcheck:
            test: 'mysql -u root -proot -D zenstruck_foundry -e "SELECT 1"'
            timeout: 120s
            retries: 60
            interval: 2s

    mongo:
        container_name: foundry_mongo
        image: mongo:4.4
        tmpfs:
            - /data
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
            - MONGO_INITDB_DATABASE=mongo
            - MONGO_NON_ROOT_USERNAME=mongo
            - MONGO_NON_ROOT_PASSWORD=mongo
        ports:
            - ${MONGO_PORT:-27017}:27017
        volumes:
            - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
        healthcheck:
            test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet
            timeout: 10s
            retries: 10
