#!/bin/bash

set -o errexit
set -o nounset

### >> load env vars from .env files if not in CI and not from a composer script
if [ -z "${CI:-}" ] ; then
  source .env

  if [ -f .env.local ]; then
    source .env.local
  fi
fi
### <<

### >> actually execute PHPUnit with the right options
DAMA_EXTENSION="DAMA\DoctrineTestBundle\PHPUnit\PHPUnitExtension"
FOUNDRY_EXTENSION="Zenstruck\Foundry\PHPUnit\FoundryExtension"

PHPUNIT_EXEC="vendor/bin/phpunit -c phpunit.xml.dist"
PHPUNIT_EXEC="${PHPUNIT_EXEC} --extension Zenstruck\Foundry\Tests\Fixture\DoctrineCascadeRelationship\PhpUnitTestExtension"

if [ "${USE_DAMA_DOCTRINE_TEST_BUNDLE:-0}" = "1" ]; then
  PHPUNIT_EXEC="${PHPUNIT_EXEC} --extension ${DAMA_EXTENSION}"
fi

PHPUNIT_EXEC="${PHPUNIT_EXEC} --extension ${FOUNDRY_EXTENSION}"

if [ "${WITH_LOWEST_DEPENDENCIES:-0}" = "1" ]; then
  PHPUNIT_EXEC="${PHPUNIT_EXEC} --do-not-fail-on-deprecation --do-not-fail-on-phpunit-deprecation"
fi

PHPUNIT_EXEC="${PHPUNIT_EXEC} $*"

echo "${PHPUNIT_EXEC}"
$PHPUNIT_EXEC
### <<
