<?php

/*
 * This file is part of the zenstruck/foundry package.
 *
 * (c) Kevin Bond <kevinbond@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zenstruck\Foundry;

use Faker;

/**
 * @author Nicolas PHILIPPE <nikophil@gmail.com>
 *
 * @internal
 */
final class FakerAdapter
{
    private static ?int $fakerSeed = null;
    private ?int $forcedFakerSeed;

    private static bool $fakerSeedHasBeenSet = false;
    private static bool $fakerSeedIsForced = false;
    private static ?string $currentTestId = null;

    public function __construct(
        private readonly Faker\Generator $faker,
        ?int $forcedFakerSeedFromConfig = null,
        ?int $forcedFakerSeedFromEnv = null,
        private bool $manageFakerSeed = true,
    ) {
        $this->forcedFakerSeed = $forcedFakerSeedFromEnv ?? $forcedFakerSeedFromConfig;
    }

    public static function fakerSeed(): ?int
    {
        return self::$fakerSeed;
    }

    public function faker(): Faker\Generator
    {
        if (!self::$fakerSeedHasBeenSet) {
            $this->seedFaker();
        }

        return $this->faker;
    }

    public static function resetFakerSeed(?int $forcedFakerSeed = null): void
    {
        self::$fakerSeed = $forcedFakerSeed;
        self::$fakerSeedIsForced = null !== $forcedFakerSeed;
        self::$fakerSeedHasBeenSet = false;
    }

    public static function reset(): void
    {
        self::$fakerSeedHasBeenSet = false;
        self::$currentTestId = null;
    }

    public static function setCurrentTestId(?string $testId): void
    {
        self::$currentTestId = $testId;
    }

    private function seedFaker(): void
    {
        self::$fakerSeedHasBeenSet = true;

        if (null !== $this->forcedFakerSeed) {
            // an explicitly forced seed stays in effect for the whole run, even when Foundry does not manage it
            self::$fakerSeedIsForced = true;
        }

        // when Foundry neither manages the seed nor was given an explicit one, leave faker completely untouched:
        // this prevents collisions in some edge cases where the end-user does not reset its db on each test
        // see https://github.com/zenstruck/foundry/issues/1069
        // this cannot rely on the static seed alone: it may have been generated by another adapter, typically
        // the one built by UnitTestConfig, which has no access to the bundle's "manage_seed" config
        if (!$this->manageFakerSeed && !self::$fakerSeedIsForced) {
            return;
        }

        $seed = self::$fakerSeed ??= $this->forcedFakerSeed ?? \random_int(1, 1000000);

        $this->faker->seed(self::seedForCurrentTest($seed));
    }

    /**
     * Each test gets its own seed, derived from the run's seed, so that tests no longer generate the same
     * values as one another, while a given test still replays identically when run in isolation with the
     * same run seed. Without a test id, Foundry's PHPUnit extension is not in use (PHPUnit 9/10, or the
     * deprecated Factories trait): the run's seed is then used as-is.
     */
    private static function seedForCurrentTest(int $runSeed): int
    {
        return null === self::$currentTestId ? $runSeed : \crc32($runSeed.'::'.self::$currentTestId);
    }
}
