<?php

declare(strict_types=1);

/*
 * This file is part of the zenstruck/foundry package.
 *
 * (c) Kevin Bond <kevinbond@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zenstruck\Foundry\Tests\Integration\InMemory;

use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\RequiresPhpunit;
use PHPUnit\Framework\Attributes\RequiresPhpunitExtension;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Attribute\ResetDatabase;
use Zenstruck\Foundry\InMemory\AsInMemoryTest;
use Zenstruck\Foundry\PHPUnit\FoundryExtension;
use Zenstruck\Foundry\Tests\Fixture\Entity\Address;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\AddressFactory;
use Zenstruck\Foundry\Tests\Integration\RequiresORM;
use function Zenstruck\Foundry\Persistence\delete;

/**
 * @author Nicolas PHILIPPE <nikophil@gmail.com>
 * @requires PHPUnit >=11.4
 */
#[RequiresPhpunit('>=11.4')]
#[RequiresPhpunitExtension(FoundryExtension::class)]
#[ResetDatabase]
final class InMemoryAttributeOnMethodTest extends KernelTestCase
{
    use RequiresORM;

    private EntityManagerInterface $entityManager;

    protected function setUp(): void
    {
        $this->entityManager = self::getContainer()->get(EntityManagerInterface::class); // @phpstan-ignore assign.propertyType
    }

    /**
     * @test
     */
    #[Test]
    #[AsInMemoryTest]
    public function create_one_does_not_persist_in_database(): void
    {
        $address = AddressFactory::createOne();
        self::assertInstanceOf(Address::class, $address);

        self::assertSame(0, $this->entityManager->getRepository(Address::class)->count([]));

        // id is autogenerated from the db, then it should be null
        self::assertNull($address->id);
    }

    /**
     * @test
     */
    #[Test]
    public function not_in_memory_test(): void
    {
        $address = AddressFactory::createOne();
        self::assertInstanceOf(Address::class, $address);

        self::assertSame(1, $this->entityManager->getRepository(Address::class)->count([]));

        self::assertNotNull($address->id);

        delete($address);
    }
}
