<?php

declare(strict_types=1);

/*
 * This file is part of the zenstruck/foundry package.
 *
 * (c) Kevin Bond <kevinbond@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Zenstruck\Foundry\Tests\Integration\InMemory;

use Doctrine\ORM\EntityManagerInterface;
use PHPUnit\Framework\Attributes\RequiresPhpunit;
use PHPUnit\Framework\Attributes\RequiresPhpunitExtension;
use PHPUnit\Framework\Attributes\Test;
use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Zenstruck\Foundry\Attribute\WithStory;
use Zenstruck\Foundry\InMemory\AsInMemoryTest;
use Zenstruck\Foundry\PHPUnit\FoundryExtension;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;
use Zenstruck\Foundry\Tests\Fixture\Entity\Address;
use Zenstruck\Foundry\Tests\Fixture\Entity\Category;
use Zenstruck\Foundry\Tests\Fixture\Entity\Contact;
use Zenstruck\Foundry\Tests\Fixture\Entity\GenericEntity;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Address\AddressFactory;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Category\CategoryFactory;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\Contact\ContactFactory;
use Zenstruck\Foundry\Tests\Fixture\Factories\Entity\GenericEntityFactory;
use Zenstruck\Foundry\Tests\Fixture\InMemory\InMemoryAddressRepository;
use Zenstruck\Foundry\Tests\Fixture\InMemory\InMemoryContactRepository;
use Zenstruck\Foundry\Tests\Fixture\Stories\EntityStory;
use Zenstruck\Foundry\Tests\Integration\RequiresORM;

/**
 * @author Nicolas PHILIPPE <nikophil@gmail.com>
 * @requires PHPUnit >=11.4
 */
#[RequiresPhpunit('>=11.4')]
#[RequiresPhpunitExtension(FoundryExtension::class)]
#[AsInMemoryTest]
final class InMemoryTest extends KernelTestCase
{
    use Factories;
    use RequiresORM;
    use ResetDatabase;

    private InMemoryAddressRepository $addressRepository;
    private InMemoryContactRepository $contactRepository;

    private EntityManagerInterface $entityManager;

    protected function setUp(): void
    {
        $this->addressRepository = self::getContainer()->get(InMemoryAddressRepository::class); // @phpstan-ignore assign.propertyType
        $this->contactRepository = self::getContainer()->get(InMemoryContactRepository::class); // @phpstan-ignore assign.propertyType

        $this->entityManager = self::getContainer()->get(EntityManagerInterface::class); // @phpstan-ignore assign.propertyType
    }

    /**
     * @test
     */
    #[Test]
    public function create_one_does_not_persist_in_database(): void
    {
        $address = AddressFactory::createOne();
        self::assertInstanceOf(Address::class, $address);

        self::assertSame(0, $this->entityManager->getRepository(Address::class)->count([]));

        // id is autogenerated from the db, then it should be null
        self::assertNull($address->id);

        self::assertCount(1, AddressFactory::repository());
    }

    /**
     * @test
     */
    #[Test]
    public function create_many_does_not_persist_in_database(): void
    {
        $addresses = AddressFactory::createMany(2);
        self::assertContainsOnlyInstancesOf(Address::class, $addresses);

        self::assertSame(0, $this->entityManager->getRepository(Address::class)->count([]));

        foreach ($addresses as $address) {
            // id is autogenerated from the db, then it should be null
            self::assertNull($address->id);
        }

        self::assertCount(2, AddressFactory::repository());
    }

    /**
     * @test
     */
    #[Test]
    public function object_should_be_accessible_from_in_memory_repository(): void
    {
        $address = AddressFactory::createOne();

        self::assertSame([$address], $this->addressRepository->_all());

        self::assertCount(1, AddressFactory::repository());
    }

    /**
     * @test
     */
    #[Test]
    public function nested_objects_should_be_accessible_from_their_respective_repository(): void
    {
        $contact = ContactFactory::createOne();

        self::assertSame([$contact], $this->contactRepository->_all());
        self::assertSame([$contact->getAddress()], $this->addressRepository->_all());

        self::assertSame(0, $this->entityManager->getRepository(Address::class)->count([]));
        self::assertSame(0, $this->entityManager->getRepository(Contact::class)->count([]));

        self::assertCount(1, ContactFactory::repository());
        self::assertCount(1, AddressFactory::repository());
    }

    /**
     * @test
     */
    #[Test]
    public function can_use_generic_repository(): void
    {
        $category = CategoryFactory::createOne([
            'contacts' => ContactFactory::new()->many(2),
        ]);

        self::assertSame(0, $this->entityManager->getRepository(Category::class)->count([]));

        self::assertSame($this->contactRepository->_all(), $category->getContacts()->toArray());

        self::assertCount(2, ContactFactory::repository());
        self::assertCount(1, CategoryFactory::repository());
    }

    /**
     * @test
     */
    #[Test]
    public function one_to_many(): void
    {
        $category = CategoryFactory::createOne([
            'contacts' => ContactFactory::new()->many(2),
        ]);

        $this->assertCount(2, $category->getContacts());

        foreach ($category->getContacts() as $contact) {
            $this->assertSame($category, $contact->getCategory());
        }
    }

    /**
     * @test
     */
    #[Test]
    public function inversed_one_to_one(): void
    {
        $address = AddressFactory::createOne(['contact' => ContactFactory::new()]);

        self::assertNotNull($address->getContact());
        self::assertSame($address, $address->getContact()->getAddress());

        self::assertCount(1, ContactFactory::repository());
        self::assertCount(1, AddressFactory::repository());
    }

    #[Test]
    #[WithStory(EntityStory::class)]
    public function can_use_with_story_and_in_memory(): void
    {
        GenericEntityFactory::repository()->assert()->count(2);

        self::assertSame(0, $this->entityManager->getRepository(GenericEntity::class)->count([]));
    }
}
