name: 'Packages Split'

on:
  push:
    branches: [2.x]
    tags: ['v*']
  workflow_dispatch: ~

jobs:
  packages_split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - if: "!startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_FOUNDRY_BEHAT }}
        with:
          package_directory: 'src/Test/Behat'
          repository_organization: 'zenstruck'
          repository_name: 'foundry-behat'
          user_name: 'nikophil'
          user_email: 'nikophil@gmail.com'
          branch: '2.x'

      - if: "startsWith(github.ref, 'refs/tags/')"
        uses: danharrin/monorepo-split-github-action@v2.4.5
        env:
          GITHUB_TOKEN: ${{ secrets.SPLIT_FOUNDRY_BEHAT }}
        with:
          tag: ${{ github.ref_name }}
          package_directory: 'src/Test/Behat'
          repository_organization: 'zenstruck'
          repository_name: 'foundry-behat'
          user_name: 'nikophil'
          user_email: 'nikophil@gmail.com'
          branch: '2.x'
