name: PHP CS-Fixer

on:
  push:
    paths:
      - .github/workflows/cs-fixer.yml
      - src/**
      - tests/**
      - config/**
      - utils/**
      - .php-cs-fixer.dist.php

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  fixcs:
    name: Run php-cs-fixer
    needs: sync-with-template
    if: (github.event_name == 'push' || github.event_name == 'schedule') && !startsWith(github.ref, 'refs/tags') && github.repository_owner == 'zenstruck'
    runs-on: ubuntu-latest
    steps:
      - uses: zenstruck/.github/actions/php-cs-fixer@main
        with:
          php: 8.1
          key: ${{ secrets.GPG_PRIVATE_KEY }}
          token: ${{ secrets.COMPOSER_TOKEN }}

  sync-with-template:
    name: Sync meta files
    if: (github.event_name == 'push' || github.event_name == 'schedule') && !startsWith(github.ref, 'refs/tags') && github.repository_owner == 'zenstruck'
    runs-on: ubuntu-latest
    steps:
      - uses: zenstruck/.github/actions/sync-with-template@main
        with:
          key: ${{ secrets.GPG_PRIVATE_KEY }}
          token: ${{ secrets.COMPOSER_TOKEN }}
          phpcsconfig: false
