name: Rector Rules Test

on:
  push:
    paths:
      - 'utils/rector/**'
  pull_request:
    paths:
      - 'utils/rector/**'
  schedule:
    - cron: '0 0 1,16 * *'

jobs:
  test-rector-rules:
    name: Test rector rules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.4
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v2
        with:
          composer-options: --prefer-dist

      - name: Install Rector & PHPStan
        run: |
          composer bin phpstan install
          composer bin rector install

      - name: Test
        run: vendor/bin/phpunit -c phpunit-rector.xml.dist
        shell: bash

      - name: Static analysis
        run: bin/tools/rector/vendor/phpstan/phpstan/phpstan analyse -c utils/rector/phpstan.neon
        shell: bash
